logging:
  level:
    root: TRACE
    org.apache.tomcat: INFO
    org.apache.tomcat.util.net: WARN
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
  jwt:
    secret: 5161127a80ff47a1855176c345a1de39833b486ea3dd40629081ab0370a1632c87496492fb634c60a458182c69a7f0d0
  user:
    name: user
    password: password


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization_db
    username: authorization
    password: 

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db-changelog.yaml
    default-schema: public
multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/authorization_db?useSSL=false
        username: authorization
        password: ZXR6E70JpBa1
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: masterdb-connection-pool

    dataSources:
      -
        tenantId: tenant_1
        url: jdbc:mysql://localhost:3306/tenant_1_db?useSSL=false
        username: tenant_1
        password: BtJ3iUORJ6V*
        driverClassName: com.mysql.cj.jdbc.Driver
      -
        tenantId: tenant_2
        url: jdbc:mysql://localhost:3306/tenant_2_db?useSSL=false
        username: tenant_2
        password: Qo6ny.0!th1V
        driverClassName: com.mysql.cj.jdbc.Driver