logging:
  level:
    root: TRACE
    org.apache.tomcat: INFO
    org.apache.tomcat.util.net: WARN
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
  jwt:
    secret: 5161127a80ff47a1855176c345a1de39833b486ea3dd40629081ab0370a1632c87496492fb634c60a458182c69a7f0d0
  user:
    name: user
    password: password


spring:
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool
      connection-test-query: select 1
      driverClassName: com.mysql.cj.jdbc.Driver
      show-sql: true
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      allow_update_outside_transaction: false
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db-changelog.yaml
    default-schema: public
multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/master_db
        username: master
        password: Avt85288,akO
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: masterdb-connection-pool
        show-sql: true
        generate-ddl: true
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
